<a href="https://colab.research.google.com/github/ashfaq-polit/Large_language_models/blob/master/Reranking_RAG_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install sentence_transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 118.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 95.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 52.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 42.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 20.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 106.6 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjit

In [1]:
documents = [
    "This is a list which containing sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings.",
    "Understanding document structure aids in keyword extraction.",
    "Efficient keyword extraction enhances search accuracy.",
    "Semantic similarity improves document retrieval performance.",
    "Machine learning algorithms can optimize keyword extraction methods."
]

In [3]:
from sentence_transformers import SentenceTransformer

# Load pre-trained Sentence Transformer model
model_name = 'sentence-transformers/paraphrase-xlm-r-multilingual-v1'

model = SentenceTransformer(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
documents

['This is a list which containing sample documents.',
 'Keywords are important for keyword-based search.',
 'Document analysis involves extracting keywords.',
 'Keyword-based search relies on sparse embeddings.',
 'Understanding document structure aids in keyword extraction.',
 'Efficient keyword extraction enhances search accuracy.',
 'Semantic similarity improves document retrieval performance.',
 'Machine learning algorithms can optimize keyword extraction methods.']

In [5]:
document_embeddings = model.encode(documents)

len(document_embeddings)

8

In [7]:
for i, embedding in enumerate(document_embeddings):
    print(f"Document {i+1} embedding: {embedding}")

len(document_embeddings[0])



Document 1 embedding: [ 0.10894684  0.07812069  0.11626545 -0.31912494  0.46890226  0.43514422
  0.01453741  0.44238734  0.297164   -0.18982689  0.07389078 -0.2786491
  0.21338142 -0.12077019  0.17891686 -0.00789886  0.04754868 -0.18204565
  0.34227124 -0.06994262 -0.1428871   0.5714126  -0.11153255 -0.17895411
  0.01523131  0.26105717 -0.20555824  0.0520311  -0.02810762  0.2387324
  0.0120698   0.04404949  0.02242333 -0.1389516  -0.7410038   0.2560103
  0.08149669  0.1882047  -0.41237688  0.11368611  0.2812117   0.0586091
 -0.17318787  0.3354915   0.21803696 -0.0509073  -0.05457808 -0.87384796
 -0.24082267  0.32007006  0.4476167   0.06347848  0.5357485   0.16607259
 -0.3319701   0.33393654  0.28615916 -0.54195684 -0.27132413  0.24881177
 -0.23919374 -0.46926284  0.13836558  0.3784287  -0.0130443   0.01990617
  0.32365105  0.45857537  0.07600275  0.25299606 -0.42938974  0.10051928
 -0.3304261  -0.69876474  0.01035889  0.05666551  0.14731245 -0.47082353
  0.08064     0.33870456 -0.27278

768

In [8]:
query = "Natural language processing techniques enhance keyword extraction efficiency."

query_embedding = model.encode(query)

print("Query embedding:", query_embedding)

Query embedding: [ 3.42821240e-01  3.26170504e-01  7.73252221e-03  1.60758272e-02
  2.38517709e-02 -2.52880484e-01  8.15470070e-02  1.37177438e-01
  3.33291799e-01  3.65743376e-02 -9.28227082e-02 -3.43726009e-01
  7.12015107e-02  9.48833764e-01 -9.41291228e-02 -7.96414435e-01
 -3.20592284e-01 -2.67564476e-01  2.08664358e-01  7.99599811e-02
  7.93344900e-03 -5.22295646e-02 -1.00512616e-01 -2.04229891e-01
  2.19562605e-01  7.67738819e-02  1.25881582e-01  2.90843964e-01
 -4.99190956e-01  2.27709055e-01 -1.94742545e-01  7.21395984e-02
 -4.56502102e-03  1.21945649e-01 -1.46225840e-01 -9.64744091e-02
  1.02258258e-01 -2.04421267e-01 -3.95658046e-01  7.32253343e-02
  1.10103972e-01  4.84611362e-01  1.04519293e-01  3.86131942e-01
 -1.68697566e-01 -2.11251289e-01 -6.38036489e-01 -4.32641715e-01
  2.74458945e-01  9.64056402e-02 -1.30053446e-01  5.76566644e-02
  8.07963461e-02  6.48147985e-02 -2.14207522e-03  2.29773894e-01
 -6.66050762e-02  3.07675451e-01  2.11779445e-01 -1.57844380e-01
  9.7886

In [9]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(np.array([query_embedding]), document_embeddings)

similarities

array([[0.16948138, 0.45802265, 0.5675692 , 0.44123274, 0.6316116 ,
        0.75214124, 0.550352  , 0.7448165 ]], dtype=float32)

In [11]:
most_similar_index = np.argmax(similarities)

most_similar_index

np.int64(5)

In [12]:
most_similar_document = documents[most_similar_index]

most_similar_document

'Efficient keyword extraction enhances search accuracy.'

In [13]:
similarity_score = similarities[0][most_similar_index]

similarity_score

np.float32(0.75214124)

In [14]:
sorted_indices = np.argsort(similarities[0])[::-1]

sorted_indices

array([5, 7, 4, 2, 6, 1, 3, 0])

In [15]:
ranked_documents = [(documents[i], similarities[0][i]) for i in sorted_indices]

ranked_documents

[('Efficient keyword extraction enhances search accuracy.',
  np.float32(0.75214124)),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  np.float32(0.7448165)),
 ('Understanding document structure aids in keyword extraction.',
  np.float32(0.6316116)),
 ('Document analysis involves extracting keywords.', np.float32(0.5675692)),
 ('Semantic similarity improves document retrieval performance.',
  np.float32(0.550352)),
 ('Keywords are important for keyword-based search.', np.float32(0.45802265)),
 ('Keyword-based search relies on sparse embeddings.', np.float32(0.44123274)),
 ('This is a list which containing sample documents.', np.float32(0.16948138))]

In [16]:
print("Ranked Documents:")
for rank, (document, similarity) in enumerate(ranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Ranked Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521412372589111
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448164820671082
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.6316115856170654
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5675691962242126
Rank 5: Document - 'Semantic similarity improves document retrieval performance.', Similarity Score - 0.5503519773483276
Rank 6: Document - 'Keywords are important for keyword-based search.', Similarity Score - 0.4580226540565491
Rank 7: Document - 'Keyword-based search relies on sparse embeddings.', Similarity Score - 0.44123274087905884
Rank 8: Document - 'This is a list which containing sample documents.', Similarity Score - 0.16948138177394867


In [17]:
print("Top 4 Documents:")
for rank, (document, similarity) in enumerate(ranked_documents[:4], start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521412372589111
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448164820671082
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.6316115856170654
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5675691962242126


# **Re-Ranking**

In [18]:
!pip install rank_bm25

In [19]:
top_4_documents = [doc[0] for doc in ranked_documents[:4]]

top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [20]:
tokenized_top_4_documents = [doc.split() for doc in top_4_documents]

tokenized_top_4_documents

[['Efficient', 'keyword', 'extraction', 'enhances', 'search', 'accuracy.'],
 ['Machine',
  'learning',
  'algorithms',
  'can',
  'optimize',
  'keyword',
  'extraction',
  'methods.'],
 ['Understanding',
  'document',
  'structure',
  'aids',
  'in',
  'keyword',
  'extraction.'],
 ['Document', 'analysis', 'involves', 'extracting', 'keywords.']]

In [21]:
tokenized_query = query.split()

tokenized_query

['Natural',
 'language',
 'processing',
 'techniques',
 'enhance',
 'keyword',
 'extraction',
 'efficiency.']

In [24]:
from rank_bm25 import BM25Okapi

bm25=BM25Okapi(tokenized_top_4_documents)

bm25

In [26]:
bm25_scores = bm25.get_scores(tokenized_query)

bm25_scores

array([0.1907998 , 0.16686672, 0.17803252, 0.        ])

In [27]:
sorted_indices2 = np.argsort(bm25_scores)[::-1]

sorted_indices2

array([0, 2, 1, 3])

In [28]:
reranked_documents = [(top_4_documents[i], bm25_scores[i]) for i in sorted_indices2]

reranked_documents

[('Efficient keyword extraction enhances search accuracy.',
  np.float64(0.19079979534096053)),
 ('Understanding document structure aids in keyword extraction.',
  np.float64(0.1780325227902643)),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  np.float64(0.1668667199671815)),
 ('Document analysis involves extracting keywords.', np.float64(0.0))]

In [29]:
print("Rerank of top 4 Documents:")
for rank, (document, similarity) in enumerate(reranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Rerank of top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.19079979534096053
Rank 2: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.1780325227902643
Rank 3: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.1668667199671815
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.0


# **Cross Encoder**

In [30]:
from sentence_transformers import CrossEncoder

In [31]:
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

In [33]:
pairs = []
for doc in top_4_documents:
    pairs.append([query, doc])

pairs

[['Natural language processing techniques enhance keyword extraction efficiency.',
  'Efficient keyword extraction enhances search accuracy.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Machine learning algorithms can optimize keyword extraction methods.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Understanding document structure aids in keyword extraction.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Document analysis involves extracting keywords.']]

In [34]:
scores = cross_encoder.predict(pairs)
scores

array([ 3.1378722 ,  0.84216756, -2.919298  , -2.8781877 ], dtype=float32)

In [35]:
scored_docs = zip(scores, top_4_documents)

scored_docs

In [36]:
reranked_document_cross_encoder = sorted(scored_docs, reverse=True)

reranked_document_cross_encoder

[(np.float32(3.1378722),
  'Efficient keyword extraction enhances search accuracy.'),
 (np.float32(0.84216756),
  'Machine learning algorithms can optimize keyword extraction methods.'),
 (np.float32(-2.8781877), 'Document analysis involves extracting keywords.'),
 (np.float32(-2.919298),
  'Understanding document structure aids in keyword extraction.')]